1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written Python code that provides functions and methods for performing specific tasks. These libraries are designed to help developers avoid reinventing the wheel by providing commonly used functionalities, such as data manipulation, numerical computation, web development, machine learning algorithms, and more.

We use Python libraries for several reasons:

Reusability: Libraries contain pre-written code that can be reused across different projects without the need to rewrite it.

Productivity: Libraries save time and effort by providing ready-made solutions for common tasks, allowing developers to focus on solving higher-level problems.

Functionality: Libraries often offer specialized functionalities that might be complex or time-consuming to implement from scratch.

Community Support: Popular Python libraries typically have active communities of developers contributing to their improvement, documentation, and support, which can be valuable resources for developers.

Performance: Many Python libraries are optimized for performance, leveraging underlying C or C++ implementations to provide efficient computation.

Overall, Python libraries enhance the versatility and power of the Python programming language, making it a popular choice for a wide range of applications and domains.







2. What is the difference between Numpy array and List?

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3, 4]
list1

[1, 2, 3, 4]

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

NumPy arrays and Python lists are both used to store collections of data, but there are several key differences between them:

Data Types: In a NumPy array, all elements must be of the same data type (e.g., integers, floats), whereas Python lists can contain elements of different data types.

Memory Efficiency: NumPy arrays are more memory efficient compared to Python lists. This efficiency comes from the fact that NumPy arrays are homogeneous and store data in a contiguous block of memory, while lists are heterogeneous and store references to objects.

Performance: NumPy arrays offer better performance for mathematical operations and numerical computations compared to Python lists. This performance improvement is due to NumPy's ability to leverage optimized, pre-compiled C code for many operations.

Functionality: NumPy arrays provide a wide range of built-in functions and methods for numerical operations, such as element-wise operations, linear algebra, Fourier transforms, and more. Python lists have fewer built-in functions and methods tailored specifically for numerical computations.

Syntax and Usage: NumPy arrays are created using the numpy.array() function, and their elements are accessed using indexing and slicing syntax similar to Python lists. However, NumPy arrays offer additional functionalities like broadcasting and vectorized operations, which are not available with Python lists.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
#finding Size
arr.size 

12

In [7]:
#finding Shape
arr.shape

(3, 4)

In [8]:
#finding dimension
arr.ndim

2

1. We have created a array in the variable called arr
2. Then we import the libnrary called numpy
3. After importing the numpy we have given alias as np
4. To find the shape of the data we have the method called arr.shape
5. To find the size of the data in numpy we have the method called arr.size
6. To find the dimension of the data in numpy we have the method called arr.ndim

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr[0]

array([1, 2, 3, 4])

1. First we import numpy as np
2. we have created an array using np.array in the variable called arr
3. By using slicing method in array we found the first row of the data
4. Print the result

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr[2][3]

12

1. First we import numpy as np
2. we have created an array using np.array in the variable called arr
3. By using slicing method in array we found the third row and fourth column of the data
4. Print the result

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

1. First we import numpy as np
2. we have created an array using np.array in the variable called arr
3. By using slicing method in array we found the odd indexed  element of the data
4. Print the result

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [15]:
arr = np.random.rand(3,3)
arr

array([[0.32637221, 0.52853107, 0.83479731],
       [0.55132484, 0.972044  , 0.73864886],
       [0.53232862, 0.79796634, 0.55505995]])

1. First we import numpy as np
2. we have created an array using random numbers in the variable called arr
3. By using random.rand method in array we created random numbers of 3 x 3 matrix between the value 0 and 1
4. Print the result

8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [17]:
#using rand
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.37279433, 0.2833659 , 0.43583231],
       [0.40701575, 0.5365321 , 0.81914296],
       [0.17607583, 0.56972864, 0.06225098]])

In [18]:
#using randn
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.38837324, -0.13155998, -0.10599894],
       [-1.19067287, -0.80898923,  1.38474057],
       [-1.03380481, -1.1570599 ,  0.37750391]])

1. np.random.rand: This function generates random numbers from a uniform distribution between 0 and 1.
2. np.random.randn: This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1). 

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr.ndim

2

In [32]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [33]:
arr1.ndim

3

1. Import numpy as np
2. we create a array in the variable called arr using np.array method
3. Using np.exapand_dims method it will increase the dimension of the data by 1 row wise if we put the parameter axis = 0
4. Print the result

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

1. Import numpy as np
2. we create a array in the variable called arr using np.array method
3. Using np.T method it will transpose the data
4. Print the result

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [65]:
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# 1. Index wise multiplication
arr = A * B
arr

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [68]:
# 2.Matix multiplication
C = A.T
arr = C @ B
arr

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [69]:
# 3. Add both the matix
arr = A + B
arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [70]:
# 4. Subtact matix B from A
arr = A - B
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
# 5. Subtact matix B by A
arr = B / A
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In [72]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap byte order
arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)

Original array: [1 2 3 4]
Array with swapped byte order: [16777216 33554432 50331648 67108864]


1. Import numpy as np
2. we create a array in the variable called arr using np.array method
3. Using arr.byteswap method it will swap the byte order of an array
4. Print the result

13. What is the significance of the np.linalg.inv function?

In [73]:
A = np.array([[1, 2],
              [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Original matrix:")
print(A)
print("\nInverse matrix:")
print(A_inv)

Original matrix:
[[1 2]
 [3 4]]

Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of computing the inverse of a matrix lies in various mathematical and practical applications:

Solving systems of linear equations: One of the primary uses of matrix inversion is in solving systems of linear equations. Given a system of equations in the form Ax = b, where A is a square matrix of coefficients, x is a column vector of variables, and b is a column vector of constants, you can solve for x by computing the inverse of A and then multiplying it by b: x = A⁻¹ * b.

Matrix equations: In many mathematical and engineering problems, matrices play a central role in describing relationships between variables. Inverting matrices allows you to solve matrix equations, which can arise in various contexts, such as optimization, control theory, and signal processing.

Eigenvalue and eigenvector computation: In some cases, the inverse of a matrix is needed to compute its eigenvalues and eigenvectors. These quantities are essential in various fields, including physics, engineering, and data analysis.

Numerical stability: In some cases, computing the inverse of a matrix directly may lead to numerical instability due to round-off errors. However, techniques such as LU decomposition followed by back substitution or iterative methods like the Gauss-Seidel method are often used for solving linear systems more efficiently and accurately.

It's important to note that not all matrices have inverses. A square matrix A is invertible (or nonsingular) if and only if its determinant is nonzero. If the determinant of A is zero, then the matrix is singular, and its inverse does not exist.

14. What does the np.reshape function do, and how is it used?

In [74]:
# Define an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In this example, the original array arr had 6 elements, and by reshaping it to a 2x3 matrix, the shape was changed while preserving the original data.

It's important to note that the np.reshape function does not change the original array; it returns a new array with the specified shape. Additionally, the reshaping operation must be compatible with the number of elements in the original array; otherwise, a ValueError will be raised.

In [ ]:
# Define a 2x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Define a 1x3 array
arr2 = np.array([10, 20, 30])

# Perform broadcasting in the operation
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult after broadcasting:")
print(result)